### ISSUE TITLE
[Suggestion] Fast leaves at a distance

### ISSUE THREAD

**Issue by ghost** [isXander/CullLessLeaves#19]
I propose to make the option render range foliage
What is it
This is the drawing distance at which the foliage will be in the form of a beautiful
And the foliage after drawing will become fast, that is, not transparent
This change will not be noticeable in the distance
Since the game uses anti-aliasing, there is no difference
This will increase FPS by 4 times especially at large draw distances

**Comment by isXander** [comment]
What you described are LODs (level of distance), this is easier said than done, and if made, won't come from me as I don't have any expertise in this part of minecraft.
