### ISSUE TITLE
Crash on startup, no other mods included - Fabric 0.14.7 for MC 1.19

### ISSUE THREAD

**Issue by YurgenSchn** [isXander/CullLessLeaves#20]
OS: Windows 10 21H2 on SSD
CPU: i5 10400f
GPU: RX 570 4GB
RAM: 16GB
MC: 1.19
Fabric: 0.14.7

Edit: i should also mention, it crashes in the same way with other mods too, such as Sodium, Fabric API, Indium, Cloth Config, Mod Menu...

[crash-2022-06-11_19.10.37-client.txt](https://github.com/isXander/CullLessLeaves/files/8884809/crash-2022-06-11_19.10.37-client.txt)

**Comment by isXander** [comment]
You need cloth config.

**Comment by YurgenSchn** [comment]
Ooof, my bad, i downloaded cloth config for forge... Thanks ;D
