### ISSUE TITLE
[Suggestion] Culling of mangrove roots

### ISSUE THREAD

**Issue by ghost** [isXander/CullLessLeaves#23]
I wondered if it would be possible to cull mangrove roots as they are one of the new largest blocks in the game and are similar to leaves. the model of the mangrove roots is more complicated than leaves so I can understand if this wouldn't be possible

**Comment by isXander** [comment]
Wouldn't really be effective. Mangrove roots aren't in "clumps" so nothing would actually get culled

**Comment by isXander** [comment]
Looks like Minecraft is actually good at culling mangrove roots by itself anyway. (might be sodium)
