### ISSUE TITLE
Crashes on Fabric

### ISSUE THREAD

**Issue by Owl1001** [isXander/CullLessLeaves#27]
When i include this mod in my mods folder for Minecraft 1.19, It just crashes!

**Comment by MaixGit** [comment]
Mine also crashes, but because I have 59 other mods installed there might be a conflicting one. Here's the log:
![image](https://user-images.githubusercontent.com/43832909/177479453-86ebdc26-8663-4655-853d-6ea5202ae0e3.png)

**Comment by isXander** [comment]
MoreCulling is currently incompatible.

**Comment by MaixGit** [comment]
Thank you that worked. Are there any plans for fixing the compatibility?

**Comment by isXander** [comment]
Yes

**Comment by isXander** [comment]
Fixed with v1.0.3
