### ISSUE TITLE
ClassNotFound exception on Quilt

### ISSUE THREAD

**Issue by dj-enby** [isXander/CullLessLeaves#30]
https://mclo.gs/ikx4xzU
https://i.imgur.com/qtv3qu8.png

When launching CullLessLeaves 1.0.3 alone with Quilt Loader 0.17.1-beta.6, the game crashes during preLaunch and offers very little in the error logs.

**Comment by isXander** [comment]
Looks like this version isnt compatible with Quilt. I will fix this.

**Comment by dj-enby** [comment]
Awesome, thanks! Sorry for the unhelpful title by the way, I'm new at this.

**Comment by isXander** [comment]
Don't worry, I rename most titles.
