### ISSUE TITLE
Crash on Fabric 

### ISSUE THREAD

**Issue by Auscobe** [isXander/CullLessLeaves#32]
Using Fabric Loader 0.14.6-1.18.2. This crash occurs even if Cull Less Leaves is the only mod in the mods folder.
[crash-2022-07-18_11.46.27-client.txt](https://github.com/isXander/CullLessLeaves/files/9133787/crash-2022-07-18_11.46.27-client.txt)

**Comment by isXander** [comment]
You need [Cloth Config](https://modrinth.com/mod/cloth-config)

**Comment by Auscobe** [comment]
Already had that, but tried updating it and upon further troubleshooting found it to actually/also be MoreCulling, and that it's already known to not be on your end. Sorry.

**Comment by isXander** [comment]
It is fixed in 1.19
