### ISSUE TITLE
not compatible with cloth config 9.x

### ISSUE THREAD

**Issue by fungoza** [isXander/CullLessLeaves#44]
![image](https://user-images.githubusercontent.com/68079109/210286450-4c5bbb9c-ae7b-4815-9a69-f59e46988bea.png)

**Comment by SyberiaK** [comment]
Can't reproduce that.
Also CLL **does not** have Cloth Config as a dependency... That's really strange issue.

**Comment by isXander** [comment]
you likely have a dependency override in your config.
