### ISSUE TITLE
Dependency break with More Culling

### ISSUE THREAD

**Issue by drawblank** [isXander/CullLessLeaves#45]
![image](https://user-images.githubusercontent.com/76506140/211173343-4406a4b5-8a2a-48c0-a368-413789724d18.png)
This is a similar issue to #44 , however this seems to not involve Cloth Config at all. Instead, the issue is directly related to More Culling.

**Comment by SyberiaK** [comment]
More Culling already features leaves culling. You can just delete CLL.
