### ISSUE TITLE
Minecraft 1.19.3 does not start

### ISSUE THREAD

**Issue by Nukecraft5419** [isXander/CullLessLeaves#47]
https://paste.ee/p/hOT1Z

**Comment by Timolino456** [comment]
You have to remove More Culling. Also your version of BetterHurtCam doesn't work on 1.19.3 apparently.

**Comment by Nukecraft5419** [comment]
It is incompatible with MoreCulling, I have to remove it also in versions 1.19.2 and 1.18.2 of my client I also use other mods from the creator of MoreCulling like memoryLeakFix then when I finish the list of mods used will be available on github I am still switching to the project in typescript

**Comment by isXander** [comment]
MoreCulling provides their own leave culling if you wish to use that over CLL.

**Comment by Nukecraft5419** [comment]
I prefer to use Cull Less Leaves I removed More Culling
