### ISSUE TITLE
Dont starts with mod More Culling

### ISSUE THREAD

**Issue by Energobro** [isXander/CullLessLeaves#54]
![image](https://github.com/isXander/CullLessLeaves/assets/61550676/0c569863-b491-48fe-ae62-f8733c34b914)
1.20

**Comment by 10kmotorola** [comment]
Having the same issue.

**Comment by MicrocontrollersDev** [comment]
More Culling is the one marking Cull Less Leaves as incompatible, not the other way around.
https://github.com/fxmorin/MoreCulling/blob/master/src/main/resources/fabric.mod.json#L41

Looking at More Culling's issue tracker shows https://github.com/fxmorin/MoreCulling/issues/179.

**Comment by cootshk** [comment]
more culling does the same thing as  cull less leaves, you dont need both
