### ISSUE TITLE
Not working with sodium 0.5.0

### ISSUE THREAD

**Issue by pingouyn** [isXander/CullLessLeaves#55]
Hi, I'm on fabric.
Minecraft 1.20.1.
Release 1.2.0 of CullLessLeaves doesn't seem to work at all with sodium 0.5.0 - 0.5.1 - 0.5.2.  Enabling / disabling makes no difference whatsoever to fps or graphically. Would be lovely if it could be compatible with the latest sodium as CullLessLeaves is a very useful mod indeed (I like to set mine to level 2).
Cheers!
[edit]
latest.log
https://ufile.io/px54sms8

**Comment by JTModel3** [comment]
+1 Can confirm, let me know if you need a crash report.

**Comment by Poopooracoocoo** [comment]
... you have a crash report even though OP doesn't? 

OP, since this is not a crash you won't have a crash report. You could provide your latest.log instead I suppose

**Comment by MbtMarco** [comment]
I can confirm that, same issue happen to me.

**Comment by pingouyn** [comment]
Interesting to point out that CullLessLeaves is 'based' on the mod CullLeaves?  (from the modrinth page 'Cull Less Leaves is an improved version of Cull Leaves').

CullLeaves 3.1.0 itself doesn't do anything with sodium 0.5.0, works as intended with sodium 0.5.1, but crashes the game with sodium 0.5.2.
Hope that helps.

**Comment by isXander** [comment]
Cull Less Leaves is not at all based on Cull Leaves.

**Comment by Lolothepro** [comment]
https://github.com/isXander/CullLessLeaves/blob/61719b0190db366c3f1eddce3c969bf896b7c6c8/README.md?plain=1#L2
?

**Comment by isXander** [comment]
> https://github.com/isXander/CullLessLeaves/blob/61719b0190db366c3f1eddce3c969bf896b7c6c8/README.md?plain=1#L2
> 
> 
> ?

Yes, I wrote that. It's an improved version, no code from Cull Leaves is used.

**Comment by Lolothepro** [comment]
Oh

**Comment by pingouyn** [comment]
ok, thanks for clarifying.  The wording made me think it was Cull Leaves but improved (=modified to improve it).
