### ISSUE TITLE
[Bug] Crash on startup with 1.3.0

### ISSUE THREAD

**Issue by MbtMarco** [isXander/CullLessLeaves#56]
https://mclo.gs/KEvRAZN

**Comment by MbtMarco** [comment]
The crash is not caused by Sodium but by Memory Leak Fix.

**Comment by Zorklis** [comment]
Thanks for tracking down the incompatibility, I'm experiencing the same one, don't recall this occuring on the previous version of CullLessLeaves

**Comment by MbtMarco** [comment]
It happends only with the latest version. (1.3.0)

**Comment by pingouyn** [comment]
Confirming CullLessLeaves 1.3.0 crashes with Sodium 0.5.2 and Memory Leak Fix 1.1.1.  Solved by removing Memory Leak Fix (not ideal).
latest.log
https://ufile.io/w7yhb86o

As CullLessLeaves is inspired from / based on CullLeaves, it's worth pointing out there was a similar issue with mod CullLeaves 3.1.0 not being compatible with sodium 0.5.2; this was resolved somehow in their 3.2.0 release.
I do not know if there was also an incompatibility with Memory Leak Fix.   Just a thought, maybe it's worth checking how CullLeaves solved their incompatibility issue.  PS: I do not have the knowledge to do this myself, sorry.

**Comment by isXander** [comment]
All I did is bumped mixin extras. Memory Leak Fix probably needs to do the same and stop messing with mixin plugins.

**Comment by MbtMarco** [comment]
I closed this report because the issue is caused by Memory Leak Fix and not by Cull Less Leaves.
