### ISSUE TITLE
Mod Crashed on startup with CullLessLeaves 1.3

### ISSUE THREAD

**Issue by Tri-Iris** [isXander/CullLessLeaves#57]
Not sure what happened, but it's something with sodium or something

[New Text Document.txt](https://github.com/isXander/CullLessLeaves/files/12444344/New.Text.Document.txt)

**Comment by kestivvi** [comment]
I have very similar problem at version 1.20.1 of Minecraft and 1.3.0 of CullLessLeaves. 
There is my log of Quilt modloader crash: [crash-2023-08-26_11.43.47.6467-quilt_loader.txt](https://github.com/isXander/CullLessLeaves/files/12445031/crash-2023-08-26_11.43.47.6467-quilt_loader.txt)
As well as mods that I have installed: [mods.zip](https://github.com/isXander/CullLessLeaves/files/12445040/mods.zip)

**Comment by Jim3535** [comment]
It looks like a conflict with Memory Leak Fix.

https://github.com/fxmorin/MemoryLeakFix/issues/139
